plugins {
	id 'base'
}

tasks.register("buildAll") {
	dependsOn(
		project(":common").tasks.named("build"),
		project(":targets:mc-1.21.11").tasks.named("build"),
		project(":targets:mc-26.1.2").tasks.named("build"),
		project(":targets:mc-26.2").tasks.named("build")
	)
}

tasks.named("build") {
	dependsOn(tasks.named("buildAll"))
}
